export interface Nationality {
  code: string;
  name: string;
}

export const NATIONALITIES: Nationality[] = [
  { code: 'AF', name: 'Afghan' },
  { code: 'AX', name: 'Åland Islander' },
  { code: 'AL', name: 'Albanian' },
  { code: 'DZ', name: 'Algerian' },
  { code: 'AS', name: 'American Samoan' },
  { code: 'AD', name: 'Andorran' },
  { code: 'AO', name: 'Angolan' },
  { code: 'AI', name: 'Anguillian' },
  { code: 'AQ', name: 'Antarctic' },
  { code: 'AG', name: 'Antiguan and Barbudan' },
  { code: 'AR', name: 'Argentine' },
  { code: 'AM', name: 'Armenian' },
  { code: 'AW', name: 'Aruban' },
  { code: 'AU', name: 'Australian' },
  { code: 'AT', name: 'Austrian' },
  { code: 'AZ', name: 'Azerbaijani' },
  { code: 'BS', name: 'Bahamian' },
  { code: 'BH', name: 'Bahraini' },
  { code: 'BD', name: 'Bangladeshi' },
  { code: 'BB', name: 'Barbadian' },
  { code: 'BY', name: 'Belarusian' },
  { code: 'BE', name: 'Belgian' },
  { code: 'BZ', name: 'Belizean' },
  { code: 'BJ', name: 'Beninese' },
  { code: 'BM', name: 'Bermudian' },
  { code: 'BT', name: 'Bhutanese' },
  { code: 'BO', name: 'Bolivian' },
  { code: 'BA', name: 'Bosnian and Herzegovinian' },
  { code: 'BW', name: 'Motswana' },
  { code: 'BR', name: 'Brazilian' },
  { code: 'IO', name: 'British Indian Ocean Territorian' },
  { code: 'VG', name: 'British Virgin Islander' },
  { code: 'BN', name: 'Bruneian' },
  { code: 'BG', name: 'Bulgarian' },
  { code: 'BF', name: 'Burkinabé' },
  { code: 'BI', name: 'Burundian' },
  { code: 'KH', name: 'Cambodian' },
  { code: 'CM', name: 'Cameroonian' },
  { code: 'CA', name: 'Canadian' },
  { code: 'CV', name: 'Cape Verdean' },
  { code: 'KY', name: 'Caymanian' },
  { code: 'CF', name: 'Central African' },
  { code: 'TD', name: 'Chadian' },
  { code: 'CL', name: 'Chilean' },
  { code: 'CN', name: 'Chinese' },
  { code: 'CX', name: 'Christmas Islander' },
  { code: 'CC', name: 'Cocos Islander' },
  { code: 'CO', name: 'Colombian' },
  { code: 'KM', name: 'Comoran' },
  { code: 'CG', name: 'Congolese (Republic)' },
  { code: 'CD', name: 'Congolese (DRC)' },
  { code: 'CK', name: 'Cook Islander' },
  { code: 'CR', name: 'Costa Rican' },
  { code: 'CI', name: 'Ivorian' },
  { code: 'HR', name: 'Croatian' },
  { code: 'CU', name: 'Cuban' },
  { code: 'CW', name: 'Curaçaoan' },
  { code: 'CY', name: 'Cypriot' },
  { code: 'CZ', name: 'Czech' },
  { code: 'DK', name: 'Danish' },
  { code: 'DJ', name: 'Djiboutian' },
  { code: 'DM', name: 'Dominican (Commonwealth)' },
  { code: 'DO', name: 'Dominican (Republic)' },
  { code: 'EC', name: 'Ecuadorian' },
  { code: 'EG', name: 'Egyptian' },
  { code: 'SV', name: 'Salvadoran' },
  { code: 'GQ', name: 'Equatorial Guinean' },
  { code: 'ER', name: 'Eritrean' },
  { code: 'EE', name: 'Estonian' },
  { code: 'SZ', name: 'Swazi' },
  { code: 'ET', name: 'Ethiopian' },
  { code: 'FK', name: 'Falkland Islander' },
  { code: 'FO', name: 'Faroese' },
  { code: 'FJ', name: 'Fijian' },
  { code: 'FI', name: 'Finnish' },
  { code: 'FR', name: 'French' },
  { code: 'GF', name: 'French Guianese' },
  { code: 'PF', name: 'French Polynesian' },
  { code: 'GA', name: 'Gabonese' },
  { code: 'GM', name: 'Gambian' },
  { code: 'GE', name: 'Georgian' },
  { code: 'DE', name: 'German' },
  { code: 'GH', name: 'Ghanaian' },
  { code: 'GI', name: 'Gibraltarian' },
  { code: 'GR', name: 'Greek' },
  { code: 'GL', name: 'Greenlandic' },
  { code: 'GD', name: 'Grenadian' },
  { code: 'GP', name: 'Guadeloupean' },
  { code: 'GU', name: 'Guamanian' },
  { code: 'GT', name: 'Guatemalan' },
  { code: 'GG', name: 'Guernsey' },
  { code: 'GN', name: 'Guinean' },
  { code: 'GW', name: 'Guinea-Bissauan' },
  { code: 'GY', name: 'Guyanese' },
  { code: 'HT', name: 'Haitian' },
  { code: 'HN', name: 'Honduran' },
  { code: 'HK', name: 'Hong Konger' },
  { code: 'HU', name: 'Hungarian' },
  { code: 'IS', name: 'Icelandic' },
  { code: 'IN', name: 'Indian' },
  { code: 'ID', name: 'Indonesian' },
  { code: 'IR', name: 'Iranian' },
  { code: 'IQ', name: 'Iraqi' },
  { code: 'IE', name: 'Irish' },
  { code: 'IM', name: 'Manx' },
  { code: 'IL', name: 'Israeli' },
  { code: 'IT', name: 'Italian' },
  { code: 'JM', name: 'Jamaican' },
  { code: 'JP', name: 'Japanese' },
  { code: 'JE', name: 'Jersey' },
  { code: 'JO', name: 'Jordanian' },
  { code: 'KZ', name: 'Kazakhstani' },
  { code: 'KE', name: 'Kenyan' },
  { code: 'KI', name: 'I-Kiribati' },
  { code: 'XK', name: 'Kosovar' },
  { code: 'KW', name: 'Kuwaiti' },
  { code: 'KG', name: 'Kyrgyzstani' },
  { code: 'LA', name: 'Lao' },
  { code: 'LV', name: 'Latvian' },
  { code: 'LB', name: 'Lebanese' },
  { code: 'LS', name: 'Basotho' },
  { code: 'LR', name: 'Liberian' },
  { code: 'LY', name: 'Libyan' },
  { code: 'LI', name: 'Liechtensteiner' },
  { code: 'LT', name: 'Lithuanian' },
  { code: 'LU', name: 'Luxembourger' },
  { code: 'MO', name: 'Macanese' },
  { code: 'MG', name: 'Malagasy' },
  { code: 'MW', name: 'Malawian' },
  { code: 'MY', name: 'Malaysian' },
  { code: 'MV', name: 'Maldivian' },
  { code: 'ML', name: 'Malian' },
  { code: 'MT', name: 'Maltese' },
  { code: 'MH', name: 'Marshallese' },
  { code: 'MQ', name: 'Martinican' },
  { code: 'MR', name: 'Mauritanian' },
  { code: 'MU', name: 'Mauritian' },
  { code: 'YT', name: 'Mahoran' },
  { code: 'MX', name: 'Mexican' },
  { code: 'FM', name: 'Micronesian' },
  { code: 'MD', name: 'Moldovan' },
  { code: 'MC', name: 'Monégasque' },
  { code: 'MN', name: 'Mongolian' },
  { code: 'ME', name: 'Montenegrin' },
  { code: 'MS', name: 'Montserratian' },
  { code: 'MA', name: 'Moroccan' },
  { code: 'MZ', name: 'Mozambican' },
  { code: 'MM', name: 'Burmese' },
  { code: 'NA', name: 'Namibian' },
  { code: 'NR', name: 'Nauruan' },
  { code: 'NP', name: 'Nepali' },
  { code: 'NL', name: 'Dutch' },
  { code: 'NC', name: 'New Caledonian' },
  { code: 'NZ', name: 'New Zealander' },
  { code: 'NI', name: 'Nicaraguan' },
  { code: 'NE', name: 'Nigerien' },
  { code: 'NG', name: 'Nigerian' },
  { code: 'NU', name: 'Niuean' },
  { code: 'NF', name: 'Norfolk Islander' },
  { code: 'KP', name: 'North Korean' },
  { code: 'MK', name: 'Macedonian' },
  { code: 'MP', name: 'Northern Mariana Islander' },
  { code: 'NO', name: 'Norwegian' },
  { code: 'OM', name: 'Omani' },
  { code: 'PK', name: 'Pakistani' },
  { code: 'PW', name: 'Palauan' },
  { code: 'PS', name: 'Palestinian' },
  { code: 'PA', name: 'Panamanian' },
  { code: 'PG', name: 'Papua New Guinean' },
  { code: 'PY', name: 'Paraguayan' },
  { code: 'PE', name: 'Peruvian' },
  { code: 'PH', name: 'Filipino' },
  { code: 'PN', name: 'Pitcairn Islander' },
  { code: 'PL', name: 'Polish' },
  { code: 'PT', name: 'Portuguese' },
  { code: 'PR', name: 'Puerto Rican' },
  { code: 'QA', name: 'Qatari' },
  { code: 'RE', name: 'Réunionese' },
  { code: 'RO', name: 'Romanian' },
  { code: 'RU', name: 'Russian' },
  { code: 'RW', name: 'Rwandan' },
  { code: 'BL', name: 'Saint Barthélemois' },
  { code: 'SH', name: 'Saint Helenian' },
  { code: 'KN', name: 'Kittitian and Nevisian' },
  { code: 'LC', name: 'Saint Lucian' },
  { code: 'MF', name: 'Saint-Martinois' },
  { code: 'PM', name: 'Saint-Pierrais' },
  { code: 'VC', name: 'Vincentian' },
  { code: 'WS', name: 'Samoan' },
  { code: 'SM', name: 'Sammarinese' },
  { code: 'SA', name: 'Saudi' },
  { code: 'SN', name: 'Senegalese' },
  { code: 'RS', name: 'Serbian' },
  { code: 'SC', name: 'Seychellois' },
  { code: 'SL', name: 'Sierra Leonean' },
  { code: 'SG', name: 'Singaporean' },
  { code: 'SX', name: 'Sint Maartener' },
  { code: 'SK', name: 'Slovak' },
  { code: 'SI', name: 'Slovenian' },
  { code: 'SB', name: 'Solomon Islander' },
  { code: 'SO', name: 'Somali' },
  { code: 'ZA', name: 'South African' },
  { code: 'KR', name: 'South Korean' },
  { code: 'SS', name: 'South Sudanese' },
  { code: 'ES', name: 'Spanish' },
  { code: 'LK', name: 'Sri Lankan' },
  { code: 'SD', name: 'Sudanese' },
  { code: 'SR', name: 'Surinamese' },
  { code: 'SJ', name: 'Svalbardian' },
  { code: 'SE', name: 'Swedish' },
  { code: 'CH', name: 'Swiss' },
  { code: 'SY', name: 'Syrian' },
  { code: 'TW', name: 'Taiwanese' },
  { code: 'TJ', name: 'Tajikistani' },
  { code: 'TZ', name: 'Tanzanian' },
  { code: 'TH', name: 'Thai' },
  { code: 'TL', name: 'Timorese' },
  { code: 'TG', name: 'Togolese' },
  { code: 'TK', name: 'Tokelauan' },
  { code: 'TO', name: 'Tongan' },
  { code: 'TT', name: 'Trinidadian' },
  { code: 'TN', name: 'Tunisian' },
  { code: 'TR', name: 'Turkish' },
  { code: 'TM', name: 'Turkmen' },
  { code: 'TC', name: 'Turks and Caicos Islander' },
  { code: 'TV', name: 'Tuvaluan' },
  { code: 'UG', name: 'Ugandan' },
  { code: 'UA', name: 'Ukrainian' },
  { code: 'AE', name: 'Emirati' },
  { code: 'GB', name: 'British' },
  { code: 'US', name: 'American' },
  { code: 'UY', name: 'Uruguayan' },
  { code: 'UZ', name: 'Uzbekistani' },
  { code: 'VU', name: 'Ni-Vanuatu' },
  { code: 'VA', name: 'Vatican' },
  { code: 'VE', name: 'Venezuelan' },
  { code: 'VN', name: 'Vietnamese' },
  { code: 'VI', name: 'U.S. Virgin Islander' },
  { code: 'WF', name: 'Wallisian and Futunan' },
  { code: 'EH', name: 'Sahrawi' },
  { code: 'YE', name: 'Yemeni' },
  { code: 'ZM', name: 'Zambian' },
  { code: 'ZW', name: 'Zimbabwean' },
];

export function filterNationalities(q: string): Nationality[] {
  const term = q.trim().toLowerCase();
  if (!term) return NATIONALITIES;
  const startsWith: Nationality[] = [];
  const contains: Nationality[] = [];
  for (const n of NATIONALITIES) {
    const name = n.name.toLowerCase();
    const code = n.code.toLowerCase();
    if (name.startsWith(term) || code.startsWith(term)) {
      startsWith.push(n);
    } else if (name.includes(term) || code.includes(term)) {
      contains.push(n);
    }
  }
  return [...startsWith, ...contains];
}
