export interface Nationality {
  code: string;
  name: string;
}

export const NATIONALITIES: Nationality[] = [
  { code: 'BD', name: 'Bangladeshi' },
  { code: 'IN', name: 'Indian' },
  { code: 'PK', name: 'Pakistani' },
  { code: 'NP', name: 'Nepali' },
  { code: 'LK', name: 'Sri Lankan' },
  { code: 'BT', name: 'Bhutanese' },
  { code: 'MV', name: 'Maldivian' },
  { code: 'AF', name: 'Afghan' },
  { code: 'MY', name: 'Malaysian' },
  { code: 'ID', name: 'Indonesian' },
  { code: 'SG', name: 'Singaporean' },
  { code: 'TH', name: 'Thai' },
  { code: 'PH', name: 'Filipino' },
  { code: 'VN', name: 'Vietnamese' },
  { code: 'CN', name: 'Chinese' },
  { code: 'HK', name: 'Hong Konger' },
  { code: 'TW', name: 'Taiwanese' },
  { code: 'JP', name: 'Japanese' },
  { code: 'KR', name: 'Korean' },
  { code: 'AU', name: 'Australian' },
  { code: 'NZ', name: 'New Zealander' },
  { code: 'GB', name: 'British' },
  { code: 'IE', name: 'Irish' },
  { code: 'US', name: 'American' },
  { code: 'CA', name: 'Canadian' },
  { code: 'MX', name: 'Mexican' },
  { code: 'BR', name: 'Brazilian' },
  { code: 'AR', name: 'Argentine' },
  { code: 'CL', name: 'Chilean' },
  { code: 'DE', name: 'German' },
  { code: 'FR', name: 'French' },
  { code: 'IT', name: 'Italian' },
  { code: 'ES', name: 'Spanish' },
  { code: 'PT', name: 'Portuguese' },
  { code: 'NL', name: 'Dutch' },
  { code: 'BE', name: 'Belgian' },
  { code: 'CH', name: 'Swiss' },
  { code: 'AT', name: 'Austrian' },
  { code: 'SE', name: 'Swedish' },
  { code: 'NO', name: 'Norwegian' },
  { code: 'DK', name: 'Danish' },
  { code: 'FI', name: 'Finnish' },
  { code: 'PL', name: 'Polish' },
  { code: 'CZ', name: 'Czech' },
  { code: 'HU', name: 'Hungarian' },
  { code: 'GR', name: 'Greek' },
  { code: 'TR', name: 'Turkish' },
  { code: 'RU', name: 'Russian' },
  { code: 'UA', name: 'Ukrainian' },
  { code: 'AE', name: 'Emirati' },
  { code: 'SA', name: 'Saudi Arabian' },
  { code: 'QA', name: 'Qatari' },
  { code: 'KW', name: 'Kuwaiti' },
  { code: 'BH', name: 'Bahraini' },
  { code: 'OM', name: 'Omani' },
  { code: 'JO', name: 'Jordanian' },
  { code: 'LB', name: 'Lebanese' },
  { code: 'EG', name: 'Egyptian' },
  { code: 'MA', name: 'Moroccan' },
  { code: 'TN', name: 'Tunisian' },
  { code: 'DZ', name: 'Algerian' },
  { code: 'ZA', name: 'South African' },
  { code: 'NG', name: 'Nigerian' },
  { code: 'KE', name: 'Kenyan' },
  { code: 'ET', name: 'Ethiopian' },
  { code: 'GH', name: 'Ghanaian' },
];

export function filterNationalities(q: string): Nationality[] {
  const term = q.trim().toLowerCase();
  if (!term) return NATIONALITIES.slice(0, 10);
  return NATIONALITIES.filter(
    (n) => n.name.toLowerCase().includes(term) || n.code.toLowerCase().includes(term),
  ).slice(0, 10);
}
